# -*- coding: utf-8 -*-
{
    "name": "Delivery Logistics: Delivery Date & Expeditions",
    "version": "19.0.1.0.0",
    "category": "Inventory/Delivery",
    "summary": "Unified delivery date logic, expeditions and driver tasks",
    "license": "LGPL-3",
    "author": "Custom",
    "depends": [
        "base",
        "contacts",
        "sale_management",
        "stock",
        "account",
        "fleet",
        "project",
        "mail",
        # Field Service (FSM) app – required for driver tasks and planned dates
        "industry_fsm",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "views/account_move_views.xml",
        "views/project_task_views.xml",
        "views/expedition_views.xml",
        "views/expedition_issue_wizard_views.xml",
        "views/menus.xml",
        "report/expedition_report.xml",
        "report/expedition_report_templates.xml",
    ],
    "installable": True,
    "application": True,
    "images": ["static/description/icon.png"],
    "post_init_hook": "_post_init_hook",
}
